# Claude.md Token Reduction Project Configuration

# Security settings
security:
  max_file_size: 10485760  # 10MB maximum file size
  allowed_extensions:
    - .md
    - .txt
    - .yaml
    - .yml
    - .json
  safe_directories:
    - /mnt/c/Users/tky99/dev/
    - ./
  enable_audit_log: true
  log_level: INFO

# Token reduction settings
token_reduction:
  target_reduction: 0.6  # 60% reduction target
  compression_level: medium  # low, medium, high
  preserve_formatting: true
  cache_results: true
  algorithms:
    - deduplication
    - compression
    - smart_truncation
    - context_optimization

# Processing settings
processing:
  max_concurrent_files: 5
  timeout_seconds: 30
  chunk_size: 8192
  retry_count: 3
  enable_parallel: true

# Output settings
output:
  format: markdown
  include_metadata: true
  backup_original: true
  output_directory: ./output/
  timestamp_files: true
  compression: gzip

# Performance settings
performance:
  cache_size_mb: 100
  enable_memory_optimization: true
  gc_threshold: 1000
  profiling_enabled: false

# Logging settings
logging:
  level: INFO
  file: ./logs/claudemd-token-reduction.log
  max_size_mb: 50
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"